- id: '1572452478100'
  alias: Test22
  initial_state: 'off'
  trigger:
  - entity_id: binary_sensor.tradfri_motion_sensor_2
    for: '10'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: aopa
    service: logbook.log
