- alias: Start HomeKit
  trigger:
  - event_type: zwave.network_ready
    platform: event
  - event_type: zwave.network_complete
    platform: event
  - event_type: zwave.network_complete_some_dead
    platform: event
  condition: []
  action:
  - data: {}
    service: homekit.start
  initial_state: 'on'