- alias: Person Detected Back - Notify
  trigger:
  - platform: mqtt
    topic: homeassistant/persondetected/tensorflow/back
  condition: []
  action:
  - data:
      message: Person detected in back of the house
    service: notify.notifier_telegram_events
  - data:
      data:
        photo:
          caption: Latest Back Camera Detection - Tensorflow
          file: /srv/shared-data/image_detection/tensorflow_ma_back_latest.jpg
      message: ''
    service: notify.mobile_app_bphone
  initial_state: 'on'
