- alias: Motion Front Detected - Notify On
  trigger:
  - entity_id: binary_sensor.aeotec_zw074_multisensor_gen5_sensor
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: 'on'
      qos: '0'
      retain: 'false'
      topic: homeassistant/motiondetected/front
    service: mqtt.publish
  initial_state: 'on'

