- alias: Livingroom Area Lights - Activate Cozy
  initial_state: 'on'
  description: ''
  trigger:
  - entity_id: input_select.livingroom_area_scenes
    platform: state
    to: las_cozy
  condition: []
  action:
  - entity_id: scene.livingroom_area_lights_cozy
    service: scene.turn_on
