- alias: Livingroom Area Lights - Activate Evning
  initial_state: 'on'
  description: ''
  trigger:
  - entity_id: input_select.livingroom_area_scenes
    platform: state
    to: las_evning
  condition: []
  action:
  - entity_id: scene.livingroom_area_lights_evning
    service: scene.turn_on
