- alias: Livingroom Area Lights - Activate TV
  initial_state: 'on'
  description: ''
  trigger:
  - entity_id: input_select.livingroom_area_scenes
    platform: state
    to: las_tv
  condition: []
  action:
  - entity_id: scene.livingroom_area_lights_tv
    service: scene.turn_on
