- alias: Livingroom Remote Next
  initial_state: 'on'
  description: ''
  trigger:
  - device_id: 0d9857a8ba2a463ca26599c9c1d3bad8
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - entity_id: ' input_select.livingroom_area_scenes'
    service: input_select.select_next
