- alias: Livingroom Area Lights - Activate Dinner
  initial_state: 'on'
  description: ''
  trigger:
  - entity_id: input_select.livingroom_area_scenes
    platform: state
    to: las_dinner
  condition: []
  action:
  - entity_id: scene.livingroom_area_lights_dinner
    service: scene.turn_on
