- alias: Alarm Evening Events
  description: ''
  initial_state: 'on'
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: input_boolean.alarm_armed
    state: 'on'
  action:
  - data: {}
    entity_id: light.tv_table_light_livingroom, light.dining_table_light_livingroom,light.lightbenjamin
    service: light.turn_on
  - entity_id: switch.everspring_an179_in_wall_on_off_module_switch_2
    service: switch.turn_on
  - data:
      message: ' - Lights On'
      name: Alarm Actions
    service: logbook.log
